/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Mansi1;

import com.example.Mansi1.sample.Circle;

public class Main {
   

    public static void main(String[] args) {
        Circle c=new Circle(1,"blue",3);
        System.out.println(c);
    }
}
